-- Run manually if DB_SYNCHRONIZE=false
ALTER TABLE visits ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ;
ALTER TABLE visits ADD COLUMN IF NOT EXISTS duration_min INT;
ALTER TABLE visits ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE property_locations ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE property_locations ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_kind VARCHAR(50);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'pending';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS property_id UUID;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS lead_id UUID;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
